<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SwitchRpc.Core\SwitchRpc.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
