[project]
name = "pokemon-switch-rpc"
version = "0.1.0"
requires-python = ">=3.12"

[tool.ruff]
line-length = 80
target-version = "py312"

[tool.ruff.lint]
select = [
	"E",
	"F",
	"I",
	"B",
	"UP",
	"RUF"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
line-ending = "lf"

[tool.ruff.lint.isort]
known-first-party = [
	"games",
	"rpc"
]

[tool.pyright]
venvPath = "."
venv = ".venv"