using PKHeX.Core;
using SwitchRpc.Games.Pokemon;

namespace SwitchRpc.Tests;

/// <summary>
/// Exercises the read pipeline against blank saves generated by PKHeX in
/// memory. Blank saves cannot round-trip through SaveUtil.GetSaveFile
/// (real save files are identified partly by on-disk size fingerprints),
/// so file-based identification is covered separately by the garbage-file
/// tests and by real-save integration runs.
/// </summary>
public class PlaSaveReaderTests
{
	[Fact]
	public void CanRead_PlaSave_ReturnsTrue()
	{
		Assert.True(new PlaSaveReader().CanRead(new SAV8LA()));
	}

	[Fact]
	public void CanRead_NonPlaSave_ReturnsFalse()
	{
		Assert.False(new PlaSaveReader().CanRead(new SAV9SV()));
	}

	[Fact]
	public void Read_BlankPlaSave_ReturnsZeroedState()
	{
		var state = new PlaSaveReader().Read(new SAV8LA(), "pokemon_legends_arceus");

		Assert.Equal("pokemon_legends_arceus", state.GameId);
		Assert.Equal(0L, state.PlaytimeSeconds);
		Assert.Null(state.LocationName);
		Assert.Null(state.LocationId);

		var hisui = state.Pokedex["hisui"];
		Assert.Equal(0, hisui.Seen);
		Assert.Equal(0, hisui.Caught);
		Assert.Equal(242, hisui.Total);
	}

	[Fact]
	public void Read_NonPlaSave_Throws()
	{
		Assert.Throws<ArgumentException>(
			() => new PlaSaveReader().Read(new SAV9SV(), "pokemon_legends_arceus")
		);
	}
}
