using PKHeX.Core;
using SwitchRpc.Games.Pokemon;

namespace SwitchRpc.Tests;

/// <summary>
/// Exercises the read pipeline against blank saves generated by PKHeX in
/// memory. Blank saves cannot round-trip through SaveUtil.GetSaveFile
/// (real save files are identified partly by on-disk size fingerprints),
/// so file-based identification is covered separately by the garbage-file
/// tests and by real-save integration runs.
/// </summary>
public class SvSaveReaderTests
{
	[Fact]
	public void CanRead_SvSave_ReturnsTrue()
	{
		Assert.True(new SvSaveReader().CanRead(new SAV9SV()));
	}

	[Fact]
	public void CanRead_NonSvSave_ReturnsFalse()
	{
		Assert.False(new SvSaveReader().CanRead(new SAV8LA()));
	}

	[Fact]
	public void Read_BlankSvSave_ReturnsZeroedState()
	{
		var state = new SvSaveReader().Read(new SAV9SV(), "pokemon_scarlet");

		Assert.Equal("pokemon_scarlet", state.GameId);
		Assert.Equal(0L, state.PlaytimeSeconds);
		Assert.Equal(0, state.Pokedex["paldea"].Seen);
		Assert.Equal(0, state.Pokedex["paldea"].Caught);
		Assert.Equal(400, state.Pokedex["paldea"].Total);
		Assert.Equal(200, state.Pokedex["kitakami"].Total);
		Assert.Equal(243, state.Pokedex["blueberry"].Total);
	}

	[Fact]
	public void Read_NonSvSave_Throws()
	{
		Assert.Throws<ArgumentException>(
			() => new SvSaveReader().Read(new SAV8LA(), "pokemon_scarlet")
		);
	}
}
